export const PermissionsNames = {
  setGlobalSetting: 'setGlobalSetting',
  addUser: 'addUser',
  updateUser: 'updateUser',
  deleteUser: 'deleteUser',
  addRoute: 'addRoute',
  updateRoute: 'updateRoute',
  deleteRoute: 'deleteRoute',
  addGov: 'addGov',
  updateGov: 'updateGov',
  deleteGov: 'deleteGov',
  addCity: 'addCity',
  updateCity: 'updateCity',
  deleteCity: 'deleteCity',
};
